apiVersion: v1
kind: Service
metadata:
  name: config-client
  labels:
    app: config-client
spec:
  type: NodePort
  selector:
    app: client-app
  ports:
   - port: 8080
     targetPort: 8080
     nodePort: 30080
     name: config-client
